### ISSUE TITLE
CLI output should no longer say "preview endpoint" or "static"

### ISSUE THREAD

**Issue by foxish** [signadot/cli#7]
```
Waiting (up to --wait-timeout=5m0s) for sandbox to be ready...
✓ Sandbox status: Ready: All desired workloads are available.

Dashboard page: https://app.signadot.com/sandbox/id/9df7wtlhn31h2

PREVIEW ENDPOINT    TYPE     URL
route-endpoint      fork     https://route-endpoint--sandbox-basic.preview.signadot.com
frontend-endpoint   static   https://frontend-endpoint--sandbox-basic.preview.signadot.com
```

**Comment by enisoc** [comment]
The `static` value is coming from our API server. Should we hard-code the CLI to replace it with `host`, or is there still time to change the server-side response to say `host` for the V2 API?

**Comment by foxish** [comment]
We have time to change the API response. Should be fine to make such changes for a few more days IMO. Let's do it in the server would be my suggestion.
