### ISSUE TITLE
RFE: Add signadot CLI for windows

### ISSUE THREAD

**Issue by joebowbeer** [signadot/cli#85]
Please add signadot.exe for Windows

**Comment by scott-cotton** [comment]
Hi @joebowbeer 

Thanks for the question.   As indicated in the README in this repo, we use the [community issue tracker](https://github.com/signadot/community/issues).  So, I have filed [an issue there](https://github.com/signadot/community/issues/32) citing this one.

I'll close this issue and invite you to follow or follow up on the new one.

Thanks again for your feedback!
